server:
  port: 8090

spring:
  application:
    name: "bookcase"
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
        mode: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
      springframework:
        web: INFO
        security: TRACE

library:
  baseUrl: "https://openlibrary.org"
  path: "/search.json"
  fields: "title"

#hibernate:
#  transaction:
#    jta:
#      platform:
#        enabled: true


#hibernate.transaction.jta.platform.enable=true