spring:
  datasource:
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/library"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always