DROP TABLE IF EXISTS AUTHOR CASCADE;
DROP TABLE IF EXISTS BOOK CASCADE;
DROP TABLE IF EXISTS APP_USER CASCADE;
DROP TABLE IF EXISTS USER_BOOKS CASCADE;
DROP TABLE IF EXISTS USER_FAVORITE_BOOKS CASCADE;
DROP TABLE IF EXISTS USER_WISHLIST_BOOKS CASCADE;
DROP TYPE IF EXISTS role_enum CASCADE;
DROP TYPE IF EXISTS sex CASCADE;
DROP TYPE IF EXISTS category CASCADE;
CREATE TYPE role_enum AS ENUM ('ADMIN', 'USER', 'GUEST');
CREATE TYPE sex AS ENUM ('MALE', 'FEMALE');
CREATE TYPE category AS ENUM ('PHILOSOPHY','PSYCHOLOGY', 'ROMANCE', 'ADVENTURE', 'SCIENCE_FICTION', 'CRIME', 'KIDS', 'FANTASY', 'WAR');

CREATE TABLE IF NOT EXISTS AUTHOR(
  ID BIGSERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  SEX sex NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  IS_ALIVE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK(
  ID BIGSERIAL PRIMARY KEY NOT NULL,
  AUTHOR_ID INTEGER NOT NULL REFERENCES AUTHOR(ID),
  TITLE VARCHAR(255) NOT NULL,
  PAGES INTEGER,
  CATEGORY category NOT NULL,
  READ_BOOK BOOLEAN NOT NULL,
  CREATED_AT DATE
);

CREATE TABLE IF NOT EXISTS APP_USER(
  ID BIGSERIAL PRIMARY KEY NOT NULL,
  USER_NAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  USER_ROLE role_enum NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_BOOKS(
  USER_ID BIGINT NOT NULL REFERENCES APP_USER(ID),
  BOOK_ID BIGINT NOT NULL REFERENCES BOOK(ID),
  PRIMARY KEY (USER_ID, BOOK_ID)
);

CREATE TABLE IF NOT EXISTS USER_FAVORITE_BOOKS(
  USER_ID BIGINT NOT NULL REFERENCES APP_USER(ID),
  BOOK_ID BIGINT NOT NULL REFERENCES BOOK(ID),
  PRIMARY KEY (USER_ID, BOOK_ID)
);

CREATE TABLE IF NOT EXISTS USER_WISHLIST_BOOKS(
  USER_ID BIGINT NOT NULL REFERENCES APP_USER(ID),
  BOOK_ID BIGINT NOT NULL REFERENCES BOOK(ID),
  PRIMARY KEY (USER_ID, BOOK_ID)
);