version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 8090:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=library