create sequence IF NOT EXISTS author_seq
start with 1
increment by 1;

create sequence IF NOT EXISTS book_seq
start with 1
increment by 1;

create table AUTHOR(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  SEX VARCHAR(10) NOT NULL,
  AGE INT NOT NULL,
  IS_ALIVE BIT NOT NULL
);

create table BOOK(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  AUTHOR_ID INT NOT NULL,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
  TITLE VARCHAR(255) NOT NULL,
  PAGES INT,
  CATEGORY VARCHAR(255) NOT NULL,
  READ_BOOK BIT NOT NULL,
  CREATED_AT DATE
);

--ALTER TABLE BOOK
--  ADD CONSTRAINT AUTHOR_ID
--  ADD FOREIGN KEY (AUTHOR_ID)
--  REFERENCES AUTHOR(ID)
--;